### ISSUE TITLE
Expo todo

### ISSUE THREAD

**Issue by harperreed** [harperreed/orbiting#25]
- [ ] swipe actions
   - [ ] left swipe clear
   - [ ] right swipe show menu
- [ ] menu button on web (lower left hand corner)
- [ ] better handling of resizing text
- [ ] not scrolling below the keyboard
- [ ] not scrolling at all
- [ ] login (phone maybe)
